import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { ReportDataSnapshot } from './reports.types.js';

export class PDFGeneratorService {
  async generateReportPDF(snapshot: ReportDataSnapshot): Promise<Buffer> {
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const fontMono = await pdfDoc.embedFont(StandardFonts.Courier);

    const pageWidth = 595.28; // A4 width points
    const pageHeight = 841.89; // A4 height points
    const margin = 40;
    const contentWidth = pageWidth - margin * 2;

    let page = pdfDoc.addPage([pageWidth, pageHeight]);
    let y = pageHeight - margin;

    const checkPageBreak = (neededHeight: number) => {
      if (y - neededHeight < margin + 30) {
        // Add footer to current page
        drawFooter(page, font, pdfDoc.getPageCount());
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        y = pageHeight - margin;
        drawHeader(page, font, fontBold, snapshot);
        y -= 30;
      }
    };

    const drawHeader = (p: typeof page, f: typeof font, fb: typeof fontBold, data: ReportDataSnapshot) => {
      p.drawText('BIDGUARD AI — EXPLAINABLE COMPLIANCE REPORT', {
        x: margin,
        y: pageHeight - 25,
        size: 8,
        font: fb,
        color: rgb(0.3, 0.3, 0.4),
      });
      p.drawText(`Tender: ${data.tender.referenceNumber}`, {
        x: pageWidth - margin - 140,
        y: pageHeight - 25,
        size: 8,
        font: f,
        color: rgb(0.4, 0.4, 0.5),
      });
      p.drawLine({
        start: { x: margin, y: pageHeight - 30 },
        end: { x: pageWidth - margin, y: pageHeight - 30 },
        thickness: 0.5,
        color: rgb(0.8, 0.8, 0.85),
      });
    };

    const drawFooter = (p: typeof page, f: typeof font, pageNum: number) => {
      p.drawLine({
        start: { x: margin, y: margin + 15 },
        end: { x: pageWidth - margin, y: margin + 15 },
        thickness: 0.5,
        color: rgb(0.8, 0.8, 0.85),
      });
      p.drawText('Generated by BidGuard AI for procurement decision support. Final decisions remain with authorized officer.', {
        x: margin,
        y: margin,
        size: 7,
        font: f,
        color: rgb(0.5, 0.5, 0.5),
      });
      p.drawText(`Page ${pageNum}`, {
        x: pageWidth - margin - 30,
        y: margin,
        size: 8,
        font: f,
        color: rgb(0.4, 0.4, 0.5),
      });
    };

    // --- COVER & TITLE HEADER ---
    page.drawRectangle({
      x: margin,
      y: y - 70,
      width: contentWidth,
      height: 70,
      color: rgb(0.95, 0.96, 0.99),
      borderColor: rgb(0.8, 0.85, 0.95),
      borderWidth: 1,
    });

    page.drawText('BIDGUARD AI', {
      x: margin + 15,
      y: y - 22,
      size: 10,
      font: fontBold,
      color: rgb(0.2, 0.3, 0.7),
    });

    page.drawText('EXPLAINABLE COMPLIANCE AUDIT REPORT', {
      x: margin + 15,
      y: y - 42,
      size: 14,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.2),
    });

    page.drawText(`Report Version: ${snapshot.metadata.reportVersion}  |  Generated: ${new Date(snapshot.metadata.generatedAt).toLocaleString()}  |  Engine: ${snapshot.metadata.engineVersion}`, {
      x: margin + 15,
      y: y - 58,
      size: 8,
      font: font,
      color: rgb(0.4, 0.4, 0.5),
    });

    y -= 85;

    // --- DISCLAIMER BOX ---
    page.drawRectangle({
      x: margin,
      y: y - 32,
      width: contentWidth,
      height: 32,
      color: rgb(0.98, 0.98, 0.98),
      borderColor: rgb(0.85, 0.85, 0.85),
      borderWidth: 0.5,
    });
    page.drawText(
      'DISCLAIMER: BidGuard AI provides automated evidence extraction, deterministic rule evaluation, conflict detection,',
      { x: margin + 10, y: y - 12, size: 7, font: font, color: rgb(0.3, 0.3, 0.3) }
    );
    page.drawText(
      'and decision support. Final procurement qualification, disqualification, and award decisions remain with the authorized authority.',
      { x: margin + 10, y: y - 24, size: 7, font: fontBold, color: rgb(0.2, 0.2, 0.2) }
    );

    y -= 45;

    // --- TENDER & BIDDER META SUMMARY ---
    page.drawText('TENDER & BIDDER INFORMATION', {
      x: margin,
      y: y,
      size: 10,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.3),
    });
    y -= 15;

    const tenderInfoLines = [
      `Tender Reference: ${sanitizeForPDF(snapshot.tender.referenceNumber, 100)}`,
      `Title: ${sanitizeForPDF(snapshot.tender.title, 100)}`,
      `Organization: ${sanitizeForPDF(snapshot.tender.organization, 100)}`,
      snapshot.bidder
        ? `Bidder: ${sanitizeForPDF(snapshot.bidder.legalName, 100)} (${snapshot.bidder.bidderCode})  |  Status: ${snapshot.bidder.submissionStatus}`
        : `Scope: All Tender Bidders (Tender Compliance Summary)`,
    ];

    for (const line of tenderInfoLines) {
      page.drawText(line, { x: margin + 5, y, size: 8.5, font, color: rgb(0.2, 0.2, 0.3) });
      y -= 13;
    }

    y -= 10;

    // --- EXECUTIVE SUMMARY SECTION ---
    page.drawText('EXECUTIVE COMPLIANCE SUMMARY', {
      x: margin,
      y: y,
      size: 10,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.3),
    });
    y -= 15;

    const summaryBoxWidth = (contentWidth - 15) / 4;
    const summaryBoxes = [
      { label: 'PASS', val: `${snapshot.executiveSummary.passCount}`, bg: rgb(0.9, 0.97, 0.92), fg: rgb(0.1, 0.5, 0.2) },
      { label: 'FAIL', val: `${snapshot.executiveSummary.failCount}`, bg: rgb(0.99, 0.92, 0.92), fg: rgb(0.7, 0.1, 0.1) },
      { label: 'REVIEW', val: `${snapshot.executiveSummary.reviewCount}`, bg: rgb(0.99, 0.96, 0.88), fg: rgb(0.7, 0.5, 0.1) },
      { label: 'NOT EVALUABLE', val: `${snapshot.executiveSummary.notEvaluableCount}`, bg: rgb(0.94, 0.94, 0.95), fg: rgb(0.3, 0.3, 0.4) },
    ];

    summaryBoxes.forEach((box, idx) => {
      const bx = margin + idx * (summaryBoxWidth + 5);
      page.drawRectangle({
        x: bx,
        y: y - 30,
        width: summaryBoxWidth,
        height: 30,
        color: box.bg,
        borderColor: rgb(0.85, 0.85, 0.85),
        borderWidth: 0.5,
      });
      page.drawText(box.label, { x: bx + 8, y: y - 12, size: 7.5, font: fontBold, color: box.fg });
      page.drawText(box.val, { x: bx + 8, y: y - 25, size: 11, font: fontBold, color: box.fg });
    });

    y -= 45;

    // Additional info bar
    page.drawText(
      `Total Requirements: ${snapshot.executiveSummary.totalRequirements}  |  Evidence Conflicts: ${snapshot.executiveSummary.conflictCount}  |  AI Investigations: ${snapshot.executiveSummary.investigationCount}  |  Evidence Coverage: ${snapshot.executiveSummary.coveragePercentage}%`,
      { x: margin + 5, y, size: 8, font, color: rgb(0.3, 0.3, 0.4) }
    );
    y -= 25;

    // --- REQUIREMENT BY REQUIREMENT AUDIT TRAIL ---
    page.drawText('REQUIREMENT-BY-REQUIREMENT COMPLIANCE AUDIT TRAIL', {
      x: margin,
      y,
      size: 11,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.3),
    });
    y -= 18;

    for (const item of snapshot.requirements) {
      checkPageBreak(120);

      // Requirement Header Card
      const resultBg =
        item.evaluation.result === 'PASS'
          ? rgb(0.92, 0.97, 0.93)
          : item.evaluation.result === 'FAIL'
          ? rgb(0.99, 0.92, 0.92)
          : item.evaluation.result === 'REVIEW'
          ? rgb(0.99, 0.96, 0.88)
          : rgb(0.94, 0.94, 0.95);

      const resultFg =
        item.evaluation.result === 'PASS'
          ? rgb(0.1, 0.5, 0.2)
          : item.evaluation.result === 'FAIL'
          ? rgb(0.7, 0.1, 0.1)
          : item.evaluation.result === 'REVIEW'
          ? rgb(0.7, 0.5, 0.1)
          : rgb(0.3, 0.3, 0.4);

      page.drawRectangle({
        x: margin,
        y: y - 22,
        width: contentWidth,
        height: 22,
        color: resultBg,
        borderColor: rgb(0.85, 0.85, 0.85),
        borderWidth: 0.5,
      });

      page.drawText(`${item.requirement.requirementCode}${item.requirement.clauseReference ? ` (${item.requirement.clauseReference})` : ''}`, {
        x: margin + 8,
        y: y - 14,
        size: 9,
        font: fontMono,
        color: rgb(0.2, 0.2, 0.3),
      });

      page.drawText(`RESULT: ${item.evaluation.result}`, {
        x: pageWidth - margin - 100,
        y: y - 14,
        size: 9,
        font: fontBold,
        color: resultFg,
      });

      y -= 28;

      // Requirement details text
      page.drawText(`Requirement: ${truncateText(item.requirement.requirementText, 95)}`, {
        x: margin + 5,
        y,
        size: 8,
        font: fontBold,
        color: rgb(0.15, 0.15, 0.25),
      });
      y -= 12;

      if (item.rule) {
        page.drawText(`Rule: ${item.rule.name} (${item.rule.ruleCode} v${item.rule.version})  |  Type: ${item.rule.ruleType}`, {
          x: margin + 5,
          y,
          size: 7.5,
          font,
          color: rgb(0.3, 0.3, 0.4),
        });
        y -= 12;
      }

      page.drawText(`Trace Summary: ${truncateText(item.whyExplanation.summary || item.evaluation.summary || 'Trace pending', 100)}`, {
        x: margin + 5,
        y,
        size: 7.5,
        font,
        color: rgb(0.2, 0.2, 0.3),
      });
      y -= 12;

      // Evidence list
      if (item.evidenceList.length > 0) {
        page.drawText('Submitted Evidence Sources:', { x: margin + 5, y, size: 7.5, font: fontBold, color: rgb(0.2, 0.2, 0.4) });
        y -= 10;
        for (const ev of item.evidenceList.slice(0, 3)) {
          page.drawText(`• ${ev.fieldLabel}: "${ev.rawValue}"  (Doc: ${ev.documentName}, Pg ${ev.pageNumber}, Conf: ${Math.round(ev.confidence * 100)}%)`, {
            x: margin + 15,
            y,
            size: 7,
            font,
            color: rgb(0.3, 0.3, 0.4),
          });
          y -= 10;
        }
      }

      y -= 8;
    }

    // --- CONFLICTS & INVESTIGATIONS SECTION ---
    if (snapshot.conflicts.length > 0 || snapshot.investigations.length > 0) {
      checkPageBreak(100);

      page.drawText('EVIDENCE CONFLICTS & AI INVESTIGATIONS RECORD', {
        x: margin,
        y,
        size: 10,
        font: fontBold,
        color: rgb(0.1, 0.1, 0.3),
      });
      y -= 16;

      for (const c of snapshot.conflicts) {
        checkPageBreak(30);
        page.drawText(`[CONFLICT] Severity: ${c.severity} | Field: ${c.fieldKey} | Status: ${c.status}`, {
          x: margin + 5,
          y,
          size: 8,
          font: fontBold,
          color: rgb(0.7, 0.1, 0.1),
        });
        y -= 11;
        page.drawText(`Details: ${truncateText(c.description, 100)}`, {
          x: margin + 15,
          y,
          size: 7.5,
          font,
          color: rgb(0.3, 0.3, 0.4),
        });
        y -= 14;
      }

      for (const inv of snapshot.investigations) {
        checkPageBreak(35);
        page.drawText(`[AI INVESTIGATION - AI Assisted] Status: ${inv.status} | Trigger: ${inv.triggerType}`, {
          x: margin + 5,
          y,
          size: 8,
          font: fontBold,
          color: rgb(0.2, 0.3, 0.7),
        });
        y -= 11;
        page.drawText(`Finding: ${truncateText(inv.finding || inv.summary || 'Investigation run completed', 100)}`, {
          x: margin + 15,
          y,
          size: 7.5,
          font,
          color: rgb(0.3, 0.3, 0.4),
        });
        y -= 14;
      }
    }

    // --- AUDIT TIMELINE SECTION ---
    checkPageBreak(80);
    page.drawText('CHRONOLOGICAL AUDIT TIMELINE', {
      x: margin,
      y,
      size: 10,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.3),
    });
    y -= 16;

    for (const a of snapshot.auditTimeline.slice(0, 10)) {
      checkPageBreak(15);
      page.drawText(`${new Date(a.timestamp).toLocaleString()}  |  Event: ${a.event}  |  Actor: ${a.actor}`, {
        x: margin + 5,
        y,
        size: 7.5,
        font: fontMono,
        color: rgb(0.3, 0.3, 0.4),
      });
      y -= 11;
    }

    y -= 15;

    // --- SYSTEM VERSIONS & INTEGRITY ---
    checkPageBreak(60);
    page.drawRectangle({
      x: margin,
      y: y - 40,
      width: contentWidth,
      height: 40,
      color: rgb(0.96, 0.96, 0.98),
      borderColor: rgb(0.85, 0.85, 0.9),
      borderWidth: 0.5,
    });

    page.drawText('REPORT INTEGRITY & SYSTEM VERSIONS', {
      x: margin + 10,
      y: y - 12,
      size: 8,
      font: fontBold,
      color: rgb(0.2, 0.2, 0.3),
    });

    page.drawText(
      `Snapshot ID: ${snapshot.metadata.snapshotId}  |  SHA-256 Checksum: ${snapshot.metadata.reportChecksum.substring(0, 24)}...`,
      { x: margin + 10, y: y - 24, size: 7.5, font: fontMono, color: rgb(0.3, 0.3, 0.4) }
    );

    page.drawText(
      `BidGuard v${snapshot.systemVersions.bidGuardVersion}  |  Engine v${snapshot.systemVersions.complianceEngineVersion}  |  Agent v${snapshot.systemVersions.investigationAgentVersion}  |  Completeness: ${snapshot.metadata.completenessStatus}`,
      { x: margin + 10, y: y - 34, size: 7, font, color: rgb(0.4, 0.4, 0.5) }
    );

    // Add page footer for last page
    drawFooter(page, font, pdfDoc.getPageCount());

    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  }
}

function sanitizeForPDF(text: string, maxChars: number = 200): string {
  if (!text) return '';
  const cleaned = text
    .replace(/₹/g, 'INR ')
    .replace(/[\r\n]+/g, ' ')
    .replace(/[^\x00-\x7F]/g, '')
    .trim();

  if (cleaned.length <= maxChars) return cleaned;
  return cleaned.substring(0, maxChars - 3) + '...';
}

function truncateText(text: string, maxChars: number): string {
  return sanitizeForPDF(text, maxChars);
}

export const pdfGeneratorService = new PDFGeneratorService();
