import { RuleDefinition } from './rule-schema.interface.js';
import { FieldRegistry } from './field-registry.js';
import { FinancialNormalizer } from './normalizer.js';

export interface ConvertCandidateInput {
  requirementCode: string;
  category: string;
  ruleType: string | null;
  ruleParameters: any;
  requirementText: string;
}

export class RuleConverterService {
  /**
   * Validates and converts AI Rule Candidate objects from Feature 1B into a controlled declarative JSON rule schema.
   * If invalid, ambiguous, or referencing an unregistered field, returns status = 'REVIEW'.
   */
  convertCandidateToDefinition(input: ConvertCandidateInput): {
    definition: RuleDefinition;
    isValid: boolean;
    reason: string;
  } {
    if (!input.ruleType || !input.ruleParameters) {
      return {
        definition: {
          type: 'INFORMATIONAL',
          requirementText: input.requirementText,
          note: 'No quantitative rule candidate generated by AI.',
        },
        isValid: false,
        reason: 'Requirement is informational or non-quantitative.',
      };
    }

    const params = input.ruleParameters;

    switch (input.ruleType) {
      case 'NUMERIC': {
        const metric = params.metric || 'average_annual_turnover';
        if (!FieldRegistry.isRegistered(metric)) {
          return {
            definition: {
              type: 'INFORMATIONAL',
              requirementText: input.requirementText,
              note: `Unregistered field metric: ${metric}`,
            },
            isValid: false,
            reason: `Field metric "${metric}" is not registered in FieldRegistry.`,
          };
        }

        const normalizedVal = FinancialNormalizer.parseINR(params.value);
        if (normalizedVal === null) {
          return {
            definition: {
              type: 'INFORMATIONAL',
              requirementText: input.requirementText,
              note: `Invalid numeric threshold: ${params.value}`,
            },
            isValid: false,
            reason: `Could not parse numeric threshold value "${params.value}".`,
          };
        }

        const def: RuleDefinition = {
          type: 'NUMERIC',
          metric,
          operator: params.operator || '>=',
          value: normalizedVal,
          unit: params.currency || 'INR',
        };

        return {
          definition: def,
          isValid: true,
          reason: 'Valid numeric rule candidate successfully converted.',
        };
      }

      case 'BOOLEAN': {
        const field = params.flag || params.field || 'gst_registration_valid';
        const def: RuleDefinition = {
          type: 'BOOLEAN',
          field,
          operator: 'IS_TRUE',
        };

        return {
          definition: def,
          isValid: true,
          reason: 'Valid boolean rule candidate successfully converted.',
        };
      }

      case 'PERCENTAGE': {
        const metric = params.metric || 'local_content';
        const val = parseFloat(params.value);
        if (isNaN(val) || val < 0 || val > 100) {
          return {
            definition: {
              type: 'INFORMATIONAL',
              requirementText: input.requirementText,
              note: `Invalid percentage value: ${params.value}`,
            },
            isValid: false,
            reason: `Percentage threshold "${params.value}" out of bounds.`,
          };
        }

        const def: RuleDefinition = {
          type: 'PERCENTAGE',
          metric,
          operator: params.operator || '>=',
          value: val,
        };

        return {
          definition: def,
          isValid: true,
          reason: 'Valid percentage rule candidate successfully converted.',
        };
      }

      case 'COUNT': {
        const collection = params.collection || 'similar_completed_projects';
        const val = parseInt(params.value, 10) || 1;
        const def: RuleDefinition = {
          type: 'COUNT',
          collection,
          operator: params.operator || '>=',
          value: val,
        };

        return {
          definition: def,
          isValid: true,
          reason: 'Valid count rule candidate successfully converted.',
        };
      }

      case 'TEXT_MATCH': {
        const field = params.field || 'supplier_category';
        const def: RuleDefinition = {
          type: 'TEXT_MATCH',
          field,
          operator: 'NORMALIZED_EQUALS',
          value: params.keyword || params.value || 'compliance',
        };

        return {
          definition: def,
          isValid: true,
          reason: 'Valid text match rule candidate successfully converted.',
        };
      }

      default: {
        return {
          definition: {
            type: 'INFORMATIONAL',
            requirementText: input.requirementText,
            note: `Unsupported candidate type ${input.ruleType}`,
          },
          isValid: false,
          reason: `Rule candidate type "${input.ruleType}" requires human review.`,
        };
      }
    }
  }
}

export const ruleConverterService = new RuleConverterService();
