import React from 'react';
import { ReportMetadata } from '@/types/reports';
import { FileText, Download, Eye, Clock, ShieldCheck } from 'lucide-react';
import { reportsApi } from '@/lib/api/reports.api';

interface HistoryTableProps {
  reports: ReportMetadata[];
  onSelectReport: (reportId: string) => void;
}

export const ReportHistoryTable: React.FC<HistoryTableProps> = ({ reports, onSelectReport }) => {
  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-xs mb-6 space-y-4">
      <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800/80 pb-3">
        <div>
          <h2 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <Clock className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
            Report History & Saved Snapshots ({reports.length})
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Immutable versioned compliance report snapshots generated for this tender.
          </p>
        </div>
      </div>

      {reports.length === 0 ? (
        <div className="p-8 text-center text-xs text-slate-500">
          No compliance reports generated yet. Click "Generate Report" to build the first report snapshot.
        </div>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="bg-slate-50 dark:bg-slate-800 text-slate-600 dark:text-slate-400 font-bold uppercase text-[10px] tracking-wider border-b border-slate-200 dark:border-slate-800">
                <th className="py-3 px-3">Report Version</th>
                <th className="py-3 px-3">Type</th>
                <th className="py-3 px-3">Generated By</th>
                <th className="py-3 px-3">Timestamp</th>
                <th className="py-3 px-3">Status</th>
                <th className="py-3 px-3">Checksum SHA-256</th>
                <th className="py-3 px-3 text-center">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800/70">
              {reports.map((rep) => (
                <tr key={rep.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition">
                  <td className="py-3 px-3 font-mono font-bold text-indigo-600 dark:text-indigo-400">
                    v{rep.reportVersion}
                  </td>
                  <td className="py-3 px-3 font-medium text-slate-800 dark:text-slate-200">
                    {rep.reportType === 'BIDDER_COMPLIANCE' ? 'Bidder Report' : 'Tender Report'}
                  </td>
                  <td className="py-3 px-3 text-slate-600 dark:text-slate-400">{rep.generatedBy}</td>
                  <td className="py-3 px-3 text-slate-500 font-mono text-[11px]">
                    {new Date(rep.generatedAt).toLocaleString()}
                  </td>
                  <td className="py-3 px-3">
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-400">
                      {rep.status}
                    </span>
                  </td>
                  <td className="py-3 px-3 font-mono text-[11px] text-slate-400 truncate max-w-[120px]">
                    {rep.reportChecksum}
                  </td>
                  <td className="py-3 px-3 text-center space-x-2">
                    <button
                      onClick={() => onSelectReport(rep.id)}
                      className="p-1.5 rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
                      title="View Report"
                    >
                      <Eye className="w-3.5 h-3.5 text-indigo-500" />
                    </button>
                    <a
                      href={reportsApi.getDownloadUrl(rep.id)}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-block p-1.5 rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
                      title="Download PDF"
                    >
                      <Download className="w-3.5 h-3.5 text-emerald-500" />
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};
